---
home_assistant:
  host: "<HASS_HOST>"
  token: "<HASS_TOKEN>"
  port: 8123
  location: "<ROOM NAME>"
  interval_min: 5
  sensors:
    - name: "sen55"
      device: "/dev/i2c-1"
    - name: "scd41"
      device: "/dev/i2c-1"
